{% set name = "git-subrepo" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ingydotnet/git-subrepo/archive/{{ version }}.tar.gz
  sha256: 6e4784d9739a9153377d4a00bd3256618eee732ee988b85b4c70f1ba48566458

build:
  number: 0
  script: make install
  skip: true  # [win]

requirements:
  build:
    - git
  run:
    - git

test:
  commands:
    - git subrepo --version
  requires:
    # git-subrepo requires bash >= 4.0, which isn't provided by default on osx
    # install in the test environment here, as we expect interactive users manage
    # bash outside of the specific conda environment
    #
    # git-subrepo returns an informative error message to the user to
    #
    # brew install bash
    #
    # if an updated version of bash is required
    - bash  # [osx]

about:
  home: https://github.com/ingydotnet/git-subrepo
  license: MIT
  license_family: MIT
  license_file: License
  summary: 'Git Submodule Alternative'

  description: |
    This git command "clones" an external git repo into a subdirectory of your
    repo. Later on, upstream changes can be pulled in, and local changes can be
    pushed back. Simple.
  doc_url: https://github.com/ingydotnet/git-subrepo
  dev_url: https://github.com/ingydotnet/git-subrepo

extra:
  recipe-maintainers:
    - asford
